name = "worker-ai-chat"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[env.production]
account_id = "1e610bc9bf6087591f4244e2266e01d5"
vars = { ENVIRONMENT = "production" }

[env.preview]
account_id = "1e610bc9bf6087591f4244e2266e01d5"
vars = { ENVIRONMENT = "preview" }

[placement]
mode = "smart"
